flathub/com.jetbrains.IntelliJ-IDEA-Ultimate

com.jetbrains.IntelliJ-IDEA-Ultimate.appdata.xml, com.jetbrains.IntelliJ-IDEA-Ultimate.json
=> intellij idea ultimate edition release 2018.3.4

com.jetbrains.IntelliJ-IDEA-Ultimate.appdata.xml, com.jetbrains.IntelliJ-IDEA-Ultimate.json
=> intellij idea ultimate edition release 2019.1

.gitmodules, com.jetbrains.IntelliJ-IDEA-Ultimate.appdata.xml, com.jetbrains.IntelliJ-IDEA-Ultimate.json
=> intellij idea ultimate edition release 2019.2.3

entrypoint.sh
=> Remove JAVA_TOOL_OPTIONS environment variable

com.jetbrains.IntelliJ-IDEA-Ultimate.metainfo.xml
Signed-off-by: Junjie Yuan <yuan@junjie.pro>
=> flathub bot forget update release version

com.jetbrains.IntelliJ-IDEA-Ultimate.yml, entrypoint.sh
Might as well push this patch for Ultimate as well since it's essentially the same software as Community.
Same deal as [this PR](https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/pull/70) for IntelliJ IDEA Community.
=> Add support for Discord Integration

com.jetbrains.IntelliJ-IDEA-Ultimate.metainfo.xml
Signed-off-by: Junjie Yuan <yuan@junjie.pro>
=> update version string to 2021.2

README.asciidoc, com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Use (new) logo URL from "Brand and Assets" section instead

com.jetbrains.IntelliJ-IDEA-Ultimate.metainfo.xml, com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Update to Freedesktop 21.08.0

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Enable (bundled) Git to sign commits with GnuPG

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Automatically add upstream version number to releases list in metainfo

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Integrate zypak

.gitmodules, com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Use Git version of jetbrains-flatpak-wrapper and try to pin to commit/release

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml, flathub.json
See also:
- https://github.com/flathub/com.jetbrains.GoLand/pull/71
- https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Community/pull/144
Tested on Asahi Linux
=> Enable aarch64 build

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Introduce xdg-run/docker and xdg-run/podman filesystem access

com.jetbrains.IntelliJ-IDEA-Ultimate.desktop
=> Fix Startup WM Class in desktop file

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Update runtime to Freedesktop 24.08

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Allow application to talk to the GPG agent

apply_extra.sh, com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Embed the extra_data shell script in the Flatpak manifest

com.jetbrains.IntelliJ-IDEA-Ultimate.yaml
=> Switch IDE to make use of the native launcher for better experience

README.md, com.jetbrains.IntelliJ-IDEA-Ultimate.desktop, com.jetbrains.IntelliJ-IDEA-Ultimate.json, com.jetbrains.IntelliJ-IDEA-Ultimate.metainfo.xml
update first run info (renamed to show on homepage of github) with info on how to add permission to use "flatpak-spawn"
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/issues/227
https://github.com/flathub/com.jetbrains.IntelliJ-IDEA-Ultimate/pull/228
@cardil @cxrvh
=> update first run info, remove AppMenu, clean release notes

com.jetbrains.IntelliJ-IDEA-Ultimate.json, com.jetbrains.IntelliJ-IDEA-Ultimate.metainfo.xml, idea.properties
as https://youtrack.jetbrains.com/issue/IDEA-313202 it's no more necessary
=> removed idea.properties workaround

com.jetbrains.IntelliJ-IDEA-Ultimate.json, idea.properties
=> Revert "removed idea.properties workaround"
